export const SECTION_ITEM_UPDATE = "SECTION_ITEM_UPDATE";

export const GET_SECTION_ITEM = "GET_SECTION_ITEM";

export const SECTION_FETCH = "SECTION_FETCH";

export const CLEAR_SECTION_ITEM = "CLEAR_SECTION_ITEM";

export const UPDATE_SECTION_AMOUNT="UPDATE_SECTION_AMOUNT"
